---
# settings for the bosh-config-resource pipeline
meta:
  target: ohio-cf
  url:    https://ci2.starkandwayne.com
  name:   bosh-config-resource

  initial_version: 0.0.1

  aws:
    access_key: ((aws-cfcommunity-access))
    secret_key: ((aws-cfcommunity-secret))

  dockerhub:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: cfcommunity/bosh-config-resource

  github:
    owner: cloudfoundry-community
    repo:  bosh-config-resource
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook: ((slack-webhook))
    channel: '#botspam'
